### ISSUE TITLE
Move to repo to Toblerity org

### ISSUE THREAD

**Issue by geowurster** [geowurster/fio-buffer#6]
- [x] Change ownership
- [x] Update `__source__` tag in `__init__`
- [x] Update `setup.py`

/ cc @sgillies

**Comment by sgillies** [comment]
@geowurster after you set yourself up to use 2FA on GitHub, I'll give you the Toblerity owner role as per https://github.com/Toblerity/org/issues/2 so you can copy the repo.

**Comment by geowurster** [comment]
@sgillies Done.
